name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("rmarkdown", "tools"))'

    - name: Install Sweave (if not included)
      run: |
        Rscript -e 'install.packages("utils")'

    - name: Run Makefile
      run: |
        make all
